/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tcs.tallerListas;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;


public class IngresoEstudiantes {

	public static void main(String[] args) {
		
		System.out.println("################ Ingreso de estudiantes ################");
		
		try {
			Scanner data = new Scanner(new File("src/main/resources/data.txt"));
			
			while (data.hasNextLine()) {
				String[] estData = data.nextLine().split(",");

			}
		} catch (FileNotFoundException e) {

		}
	}
}
